---
apiVersion: v1 
kind: Pod 
metadata:
  name: worker-app-pod 
  labels:
    name: worker-app-pod 
    app: voting-pod 
spec:
  containers:
    - name: worker-app-cont 
      image: dockersamples/examplevotingapp_worker